version: 2
plugins:
    phpcodesniffer:
        enabled: true
        config:
            file_extensions: "php,inc,lib"
            standard: "PSR1,PSR2"
            ignore_warnings: true
            encoding: utf-8  
    sonar-php:
        enabled: true
exclude_patterns:
    - vendor/**
    - var/cache/**
